try {
  console.log(Timmy)
}
catch(err) {
  console.log(err.name)
}

let c = 20

let b = c * 2

b

